### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by darrencauthon** [kcruby/newkcruby#11]
Do I have to be logged in in order to create/edit/delete blog posts?

**Comment by rossfuhrman** [comment]
Yes, you do have to be logged in to create a new blog post. And you can only edit your own blog posts.
But, it looks to me like it would be possible to delete someone else's blog post since the destroy action only looks for the blog to delete based on the id passed in. It should be limited to only finding the blog if it belongs to the current user, like it does for the edit action.

**Comment by alishersadikov** [comment]
I played around editing and deleting a blog post added by a different user. In the blog show, I noticed that edit/delete links are only exposed to the current user  and I could not delete another user's blog post. Added some feature specs to illustrate this behavior in PR #30. Please let me know if you think changing the destroy action is still needed.

**Comment by alishersadikov** [comment]
#30
